name: 'Configure AWS credentials and Login ECR'
description: 'Configure AWS credentials and Login ECR'
inputs:
  aws-access-key-id:
    description: 'aws-access-key'
    required: true
  aws-secret-access-key:
    description: 'aws-secret-access-key'
    required: true
  aws-account-id:
    description: 'aws-account-id'
    required: true
  aws-region:
    description: 'aws-region'
    required: true
  aws-role-name:
    description: 'aws-role-name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{inputs.aws-access-key-id}}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: "arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.aws-role-name }}"

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
